### PR TITLE
`in_reply_to_screen_name` should be type `string` not `number`

### PR DESCRIPTION
**Pull request by winstxnhdw**

### CODE REVIEW

**Comment by hota1024** [comment]
I'm sorry for I couldn't reply to your PR.
Thank you for fixing the Tweet type.
If it's OK with you, I want to merge your code.

**Comment by winstxnhdw** [comment]
Sure, go ahead!

**Comment by winstxnhdw** [comment]
Sure, let me close this PR and create a new fork with the appropriate changes.

**Comment by hota1024** [comment]
image

**Pull request closed without merging**
